---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault-container
        image: vault
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
          runAsUser: 0
        ports:
        - containerPort: 8200
        volumeMounts:
        - mountPath: "/vault"
          name: vault-volume
        env:
          - name: SKIP_CHOWN
            value: "true"
      volumes:
      - name: vault-volume
        persistentVolumeClaim:
          claimName: vault-claim

---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  labels:
    app: vault
spec:
  type: NodePort
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 30200
      #hostIP: 10.32.0.20
  selector:
    app: vault