kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-claim
spec:
  storageClassName: manuel
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: vault-volume
  selector:
    matchLabels:
      name: devops
